export const ADD_PRACTICE = 'ADD_PRACTICE'
export const EDIT_PRACTICE = 'EDIT_PRACTICE'
export const INCREMENT_ITERATOR_PRACTICE = 'INCREMENT_ITERATOR_PRACTICE'
export const DECREMENT_ITERATOR_PRACTICE = 'DECREMENT_ITERATOR_PRACTICE'
export const ERROR_PRACTICE = 'ERROR_PRACTICE'
export const COMPLETE_PRACTICE = 'COMPLETE_PRACTICE'
export const RESTART_PRACTICE = 'RESTART_PRACTICE'

export const TICKER_TICK = 'TICKER_TICK'

export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'

